name: "publish"
on:
  push:
    tags:
      - 'v*' # Запуск при пуше тегов v1.0, v2.1.3 и т.д.

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # Для .dmg и .app
            args: "--target universal-apple-darwin" # Сборка под Intel и M1/M2 сразу
          - platform: "ubuntu-22.04" # Для .deb и .AppImage
            args: ""
          - platform: "windows-latest" # Для .msi и .exe
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      # 1. Настройка Node.js для сборки фронтенда
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2. Настройка Rust
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # 3. Системные зависимости для Linux
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # или ubuntu-latest
        run: |
            sudo apt-get update
            sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libsoup-3.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            build-essential \
            curl \
            wget \
            pkg-config

      # 4. Установка зависимостей фронтенда
      - name: install frontend dependencies
        run: npm install # или yarn install / pnpm install

      # 5. Сборка через tauri-action
      - name: build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # __VERSION__ берется из tauri.conf.json
          releaseName: "Anilibria-rs v__VERSION__"
          releaseBody: "Automated release from GitHub Actions"
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }}
